# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  application:
    name: spring-template
  main.banner-mode: off
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template
    username: ENC(qHkOTuq+VjXI0hJmcbl2WGd9NsWbp49YSyCw3w4OSs302xgjg3MF8us+vg0szDw3)
    password: ENC(4upc5UTtwStzG9aAmPhkS2eSxZMWbgc0K4s7gv3OlcTySq1irVcFkVcz6MxQce9t)
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:/db/scripts/migration
    baseline-on-migrate: true
    baseline: 0
  # ===================================================================
  # MAIL PROPERTIES
  # ===================================================================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ENC(OMqfVCDWAZbsxXwMcu9OHTYTc6Y5lh+71US5IbIGmKlTxjq92hQIlmeEiEFonCwmqpMPVJQ+KPujZAYXig8A5A==)
    password: ENC(LHNJKyxbtfI7RguXsL1zEg0coleVYMPPlCOn1rmkGX+q3ntF5kML4OD1yDVaDBVMs1xTV4pbDrVoKCTgfzw/BA==)
    server:
      protocol: smtp
      debug: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    enabled: true
    template-loader-path: classpath:/templates
# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    Key: ENC(2EUk5DmKMQDCIgwM+JHkS8r8dmlufceXZlZOvusjN2CgE7PbInQegLT8ZAdd2DLY)
    lifeTime: 10000

# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  pattern:
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
    console: "%p, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %m%n%ex{3}"
  level:
    com.moontech: DEBUG
    org:
      springframework.data: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

# ===================================================================
# URL ENDPOINTS
# ===================================================================
api:
  uri:
    basePath: /api
    domain:
      users: /users
    data:
      modified: /{id}
      search: /{search}
      authentication: ${api.uri.domain.users}/authentication
      confirm: ${api.uri.domain.users}/confirm
      userConfirm: /confirm
      reset: /password/reset
      passwordForgot: ${api.uri.domain.users}/password/reset
  interceptorPath: "/**"
  # ===================================================================
  # MAIL TEMPLATE PROPERTIES
  # ===================================================================
  mail:
    templates:
      user: email-user-template.flth
      customer: email-customer-template.flth
      payment: email-payment-subscription-template.flth
      forgotpassword: forgot-password-template.flth
    from: ulquiorra.kurosaki50@gmail.com
    welcome: Bienvenido
    payment: Tu Recibo de la Membresía
    resetPassword: Recupera tu Contraseña
    enterpriseName: Template

  token:
    expiration: 1 # one day
# ===================================================================
# SWAGGER PROPERTIES
# ===================================================================
swagger:
  basePackage: com.moontech
  title: SERV-template-service
  descriptionApi: Template for spring projects
  version: 1.0.0
  nameDeveloper: Felipe Monzón
  contactUrl: https://felipemonzon.github.io/
  emailDeveloper: felipemonzon2705@gmail.com
  licenceUrl: https://github.com/felipemonzon/spring-template/blob/main/LICENSE
# ===================================================================
# RECAPTCHA PROPERTIES
# ===================================================================
recaptcha:
  key:
    site: ENC(ert1bsOGmE5IygKapib+W+XAYPbgyyoXMgbeC/zm3l5bHUzhJ1Nw5y2FEeMIcvQq)
    secret: ENC(+Z7kArb2U/adECWmtEyYSPyHcYFZhBxmkWWTXY+mjAa0C7DcmEi9uRUeCo9JlfvZ)
    threshold: 0.5
    url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s&remoteip=%s